# alacritty version 13.0+ config

# TODO: figure out how to import themes

[env]
TERM_PROGRAM = "Alacritty"

[window]
dimensions = { columns = 96, lines = 24 }
position = "None"
padding = { x = 12, y = 12 }
dynamic_padding = true
dynamic_title = true

[font]
normal = { family = "AnonymicePro Nerd Font", style = "Regular" }
bold = { family = "AnonymicePro Nerd Font", style = "Bold" }
italic = { family = "AnonymicePro Nerd Font", style = "Italic" }
bold_italic = { family = "AnonymicePro Nerd Font", style = "Bold Italic" }
size = 18.0

[cursor]
style = { shape = "Block", blinking = "Never" }
