# alacritty version 12.x or earlier config

# import themes
import:
  # uncomment the flavour you want below:
  - ~/.config/alacritty/themes/catppuccin/catppuccin-mocha.yml
  # - ~/.config/alacritty/themes/catppuccin/catppuccin-macchiato.yml
  # - ~/.config/alacritty/themes/catppuccin/catppuccin-frappe.yml
  # - ~/.config/alacritty/themes/catppuccin/catppuccin-latte.yml

env:
  TERM: xterm-256color
  TERM_PROGRAM: Alacritty

window:
  dimensions:
    columns: 96
    lines: 24
  # position:
  # x: 0
  # y: 0
  padding:
    x: 12
    y: 12
  dynamic_padding: true
  dynamic_title: true

  # Values for `startup_mode`:
  #   - Windowed
  #   - Maximized
  #   - Fullscreen
  # Values for `startup_mode` (macOS only):
  #   - SimpleFullscreen
  # startup_mode: Windowed

font:
  normal:
    family: AnonymicePro Nerd Font
    style: Regular
  bold:
    style: Bold
  italic:
    style: Italic
  bold_italic:
    style: Bold Italic
  size: 18.0

cursor:
  style:
    shape: Block
    blinking: Never
