################################################################
# alacritty.toml - alacritty v13.0+ config                     #
################################################################
# -> symlinked to ~/.config/alacritty/alacritty.toml           #
################################################################

# import themes
import = [
  # uncomment the flavour you want below:
  "~/.config/alacritty/themes/catppuccin/catppuccin-mocha.toml"
  # "~/.config/alacritty/themes/catppuccin/catppuccin-macchiato.toml"
  # "~/.config/alacritty/themes/catppuccin/catppuccin-frappe.toml"
  # "~/.config/alacritty/themes/catppuccin/catppuccin-latte.toml"
]

[env]
TERM = "xterm-256color"
TERM_PROGRAM = "Alacritty"

[window]
dimensions = { columns = 96, lines = 24 }
position = "None"
padding = { x = 12, y = 12 }
dynamic_padding = true
dynamic_title = true

[font]
normal = { family = "AnonymicePro Nerd Font", style = "Regular" }
bold = { family = "AnonymicePro Nerd Font", style = "Bold" }
italic = { family = "AnonymicePro Nerd Font", style = "Italic" }
bold_italic = { family = "AnonymicePro Nerd Font", style = "Bold Italic" }
size = 16.0
offset = { x = 0, y = 1 }

[cursor]
style = { shape = "Block", blinking = "Never" }

[mouse]
hide_when_typing = true
