################################################################
# homebrew taps                                                #
################################################################

tap "homebrew/cask-fonts"
tap "homebrew/aliases"
tap "homebrew/bundle"
tap "homebrew/services"

################################################################
# core formulae                                                #
################################################################

brew "antigen"                  # zsh plugin manager
brew "autojump"                 # recent directory hopper
brew "bash"                     # updated bash
brew "bat"                      # cat alternative
brew "direnv"                   # directory level envs
brew "dotbot"                   # dotfile manager
brew "dust"                     # disk space analyzer
brew "exa"                      # ls alternative
brew "exercism"                 # coding exercises
brew "ferium"                   # minecraft mod manager
brew "gh"                       # github cli
brew "git"                      # version control system
brew "glow"                     # terminal markdown viewer
# brew "gradle"                   # java build tool
brew "httpie"                   # rest client
brew "just"                     # project specific commands
brew "pastel"                   # color manipulation
# brew "podman"                   # containerization
# brew "postgresql"               # postgres DB
brew "quilt-installer"          # minecraft mod loader
brew "pre-commit"               # git hook manager
brew "pyenv"                    # python version manager
brew "rustup-init"              # rust toolchain installer
brew "scc"                      # lines of code counter
brew "starship"                 # cross-shell prompt
# brew "vercel-cli"               # deployments and hosting
# brew "viddy"                    # watch alternative
# brew "xxh"                      # ssh shell preservation
brew "yank"                     # terminal clipboard utility
brew "zsh"                      # updated z shell

################################################################
# casks                                                        #
################################################################

# cask "balenaetcher", args: { appdir: "~/Applications" } # boot drive imager
cask "bartender"                # menu bar organizer ($)
# cask "bricklink-studio"         # lego designer
cask "discord"                  # digital communities
cask "duckduckgo"               # web browser
cask "eloston-chromium"         # ungoogled chromium browser
cask "firefox"                  # web browser
cask "github"                   # git client
cask "httpie"                   # rest client
cask "hush"                     # safari content blocker
cask "hyper"                    # terminal emulator
cask "keka"                     # archive handler
cask "kekaexternalhelper"       # keka helper
cask "linear-linear"            # issue tracker
cask "logi-options-plus"        # logitech peripheral manager
cask "mactracker"               # apple product info
cask "minecraft"                # minecraft launcher
cask "obs"                      # streaming suite
cask "obsidian"                 # markdown knowledge base
# cask "podman-desktop"           # containerization
cask "protonmail-bridge"        # proton.me local IMAP bridge
cask "protonvpn"                # vpn
# cask "raspberry-pi-imager", args: { appdir: "~/Applications" } # pi boot drive imager
cask "raycast"                  # spotlight replacement
# cask "retroarch"                # video game emulation launcher
cask "spotify"                  # music and podcasts
cask "stats"                    # menu bar system stats
cask "steam"                    # video game marketplace and launcher
cask "temurin"                  # jdk
cask "vscodium"                 # editor

################################################################
# cask-fonts                                                   #
################################################################

cask "font-anonymous-pro"
cask "font-anonymice-nerd-font"

################################################################
# custom taps                                                  #
################################################################

brew "boldandbrad/tap/meeple-cli"       # board game collection manager
brew "oven-sh/bun/bun"                  # js runtime and package manager
tap "superatomic/bundle-extensions"     # extra brew commands

################################################################
# new additions (via "brew add")                               #
################################################################
cask "krita"
