################################################################
# setup (required)                                             #
################################################################

# homebrew taps #
tap "homebrew/core"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/autoupdate"
tap "homebrew/bundle"
# tap "homebrew/services"

# mac app store installer #
brew "mas"

################################################################
# core formulae                                                #
################################################################

# cli #
brew "autojump"                 # recent directory hopper
brew "bat"                      # cat alternative
brew "ddgr"                     # duckduckgo cli
brew "direnv"                   # directory level envs
# brew "docker"                   # containerization
cask "hpedrorodrigues/tools/dockutil"  # dock manager (temporary cask tap due to issues with official formula)
brew "dotbot"                   # dotfile manager
# brew "duti"                     # default app utility
brew "exa"                      # ls alternative
brew "gh"                       # github cli
brew "git"                      # version control
brew "glow"                     # terminal markdown viewer
brew "httpie"                   # rest client
brew "just"                     # project specific commands
brew "macchina"                 # system info
brew "m-cli"                    # macos cli
brew "noti"                     # trigger macos notifications
brew "pastel"                   # color manipulation
brew "pipx"                     # globally isolated pip installs
brew "scc"                      # lines of code counter
brew "starship"                 # cross-shell prompt
brew "tldr"                     # community driven man pages
brew "travis"                   # travis ci cli
brew "yank"                     # terminal clipboard utility
# brew "zsh"                      # updated z shell
brew "zsh-autosuggestions"      # zsh autosuggestions
brew "zsh-syntax-highlighting"  # zsh syntax highlighting

# dev #
# brew "asdf"                     # runtime version manager
brew "cocoapods"                # native apple development
brew "fnm"                      # nodejs version manager
# brew "nodenv"                   # nodejs version manager
brew "pnpm"                     # nodejs package installer
brew "pyenv"                    # python version manager
brew "rbenv"                    # ruby version manager
brew "rustup-init"              # rust toolchain installer
# brew "vercel-cli"               # deployments and hosting
# brew "vue-cli"                  # vue.js tooling cli

################################################################
# casks                                                        #
################################################################

# apps #
cask "aldente"                  # battery manager ($?)
cask "appcleaner"               # app uninstaller
cask "bartender"                # menu bar organizer ($)
cask "cleanshot"                # screen captures ($)
# cask "codeedit"                 # editor (not yet available)
cask "commandq"                 # delayed app quits ($)
cask "daisydisk"                # disk space visualizer ($)
cask "datweatherdoe"            # menu bar weather
cask "devutils"                 # dev utility suite ($)
cask "discord"                  # digital communities
# cask "docker"                   # containerization
cask "fig"                      # terminal autocomplete
cask "firefox"                  # web browser
cask "geekbench"                # system benchmarking
cask "github"                   # git client
# cask "hazel"                    # file automation ($$)
# cask "httpie"                   # rest client (not yet available)
cask "hush"                     # safari content blocker
cask "hyper"                    # terminal replacement
cask "keka"                     # archive handler
cask "kekaexternalhelper"       # keka helper
cask "linear-linear"            # issue tracker
cask "mactracker"               # apple product info
cask "numi"                     # notepad calculator ($?)
# cask "obs"                      # streaming suite
cask "openinterminal"           # terminal/ide finder toolbar
cask "protonmail-bridge"        # proton.me local IMAP bridge
cask "raspberry-pi-imager"      # pi boot drive imager
cask "raycast"                  # spotlight replacement
cask "rectangle"                # window management
cask "signal"                   # secure messaging
# cask "spacedrive"               # file database (not yet available)
cask "spotify"                  # music and podcasts
cask "stats"                    # menu bar system stats
cask "todoist"                  # task tracker
# cask "utm"                      # virtual machines
cask "vscodium"                 # editor

# dev #
cask "temurin"                  # jdk

# games #
cask "minecraft"                # minecraft launcher
# cask "openemu"                  # game emulator
# cask "retroarch"                # game emulator

################################################################
# cask-drivers                                                 #
################################################################

# cask "elgato-game-capture-hd"   # elgato peripheral suite
cask "logitech-options"         # logitech peripheral manager
# cask "sonos"                    # sonos sound system manager

################################################################
# cask-fonts                                                   #
################################################################

cask "font-cascadia-code"
# cask "font-caskaydia-cove-nerd-font"
cask "font-camingocode"
cask "font-fira-code"
cask "font-fira-code-nerd-font"
cask "font-inconsolata"
cask "font-inter"
cask "font-jetbrains-mono"

################################################################
# mas                                                          #
################################################################

# apps #
mas "bear", id: 1091189122          # markdown notes ($)
# mas "bitwarden", id: 1352778147     # password manager
mas "canary-mail", id: 1236045954   # email client ($)
mas "color-picker", id: 1545870783  # color picker
mas "dashlane", id: 517914548       # password manager ($)
mas "duckduckgo", id: 1482920575    # safari tracker blocker
mas "magic-lasso", id: 1198047227   # safari ad blocker
mas "numbers", id: 409203825        # spreadsheets
mas "parcel", id: 639968404         # package tracking
mas "peek", id: 1554235898          # quicklook enhancer ($)
mas "twitter", id: 1482454543       # social feed

# dev #
mas "xcode", id: 497799835          # apple ide

################################################################
# custom taps                                                  #
################################################################

tap "boldandbrad/homebrew-tap"
brew "makey-cli"                    # cli passkey maker

tap "superatomic/bundle-extensions" # additional brew commands

tap "teamookla/speedtest"
brew "speedtest"                    # cli internet speed tester

tap "zero-sh/tap"
brew "apply-user-defaults"          # macos defaults installer

################################################################
# new additions (via "brew add")                               #
################################################################

