#!/usr/bin/env zsh

# ------------------------------------------------------------ #
# macos/update_system - check for dev tools and macOS updates  #
# ------------------------------------------------------------ #
# NOTE: System updates may force a restart. Rerun unpack.sh to #
# continue.                                                    #
# ------------------------------------------------------------ #

# install command line developer tools
echo -e "\nChecking for Command Line Developer Tools..."
if [[ ! -a $(xcode-select -p 2>/dev/null) ]]; then
  echo "Installing Command Line Developer Tools. Follow the actions in the GUI."
  sudo xcode-select --install
  echo "Waiting for tools to be installed. If the operation was cancelled, hit ^C and restart this script."
  while [[ ! -a $(xcode-select -p 2>/dev/null) ]]; do
    sleep 1
  done
  echo "${GREEN_B}Command Line Developer Tools are now installed!${RESET}"
else
  echo "${GREEN_B}Command Line Developer Tools are already installed!${RESET}"
fi

# check for available software updates
# TODO: handle download only case or install only non system updates
echo
echo "Checking for available macOS software updates..."
if softwareupdate -l 2>&1 | grep -q $Q "No new software available."; then
  echo "${GREEN_B}No new software available.${RESET}"
else
  echo "Software updates available:"
  softwareupdate -l | tail -n +4

  echo -en "\n${BLUE_B}Would you like to install the available updates? This will cause a restart. (y/N):${RESET} "
  read -t $PROMPT_TIMEOUT -n 1 -r ans_update && echo
  if [[ ! $ans_update =~ ^[Yy]$ ]] ; then
    echo -e "\nSkipping system updates."
  else
    sudo softwareupdate --install --all --restart
  fi
fi
