################################################################
# Brewfile - macOS software installs                           #
################################################################
# -> dotbot symlinks this file to ~/.config/homebrew/Brewfile  #
#                                                              #
# Packages and apps to be installed / updated via Homebrew.    #
# Be sure to remove / comment out tools you do not need.       #
################################################################

################################################################
# options                                                      #
################################################################

# cask_args appdir: '~/Applications', require_sha: true

################################################################
# taps                                                         #
################################################################

# tap "homebrew/core"                   # packages & clis
# tap "homebrew/cask"                   # desktop apps
tap "homebrew/cask-fonts"             # fonts
tap "homebrew/bundle"                 # brewfile commands
tap "homebrew/services"               # system services

tap "boldandbrad/tap"                 # stuff made by me :)
tap "oven-sh/bun"                     # bun tools
tap "pkgxdev/made"                    # pkgx tools
tap "superatomic/bundle-extensions"   # extra brew commands

################################################################
# packages & command line tools                                #
################################################################

brew "antidote"                 # zsh plugin manager
brew "autojump"                 # recent directory hopper
brew "bash"                     # updated bash
brew "bat"                      # cat alternative
brew "boldandbrad/tap/meeple-cli" # board game collection manager
brew "direnv"                   # directory level envs
brew "dust"                     # disk space analyzer
brew "eza"                      # ls alternative
brew "fcp"                      # cp alternative
brew "git"                      # version control system
brew "glow"                     # terminal markdown viewer
brew "just"                     # project specific commands
brew "neovim"                   # tui editor
brew "pastel"                   # color manipulation
brew "ripgrep"                  # grep alternative
# brew "rm-improved"              # rm alternative
brew "starship"                 # cross-shell prompt
brew "tailspin"                 # log file highlighter
brew "tldr"                     # concise man pages
# brew "viddy"                    # watch alternative
brew "xdg-ninja"                # home dir cleaner
# brew "xxh"                      # ssh shell preservation
brew "yank"                     # terminal clipboard utility
brew "zsh"                      # updated z shell

################################################################
# desktop apps                                                 #
################################################################

cask "arc"                      # web browser of the future
# cask "balenaetcher"             # boot drive imager
cask "bricklink-studio"         # lego designer
cask "discord"                  # digital communities
cask "duckduckgo"               # web browser
cask "firefox"                  # web browser
cask "hush"                     # safari content blocker
cask "keka"                     # archive handler
cask "kekaexternalhelper"       # keka helper
cask "kitty"                    # terminal emulator
cask "logi-options-plus"        # logitech peripheral manager
cask "mactracker"               # apple product info
# cask "neovide"                  # neovim gui
# cask "obs"                      # streaming suite
cask "obsidian"                 # markdown knowledge base
cask "proton-drive"             # secure cloud storage
cask "protonmail-bridge"        # proton.me local IMAP bridge
cask "protonvpn"                # secure vpn
# cask "raspberry-pi-imager"      # pi boot drive imager
cask "raycast", args: { require_sha: false } # spotlight replacement
cask "spotify", args: { require_sha: false } # music and podcasts
cask "stats"                    # menu bar system stats
cask "vscodium"                 # editor

################################################################
# software development                                         #
################################################################

brew "deno"                     # js runtime and tooling
brew "exercism"                 # coding exercise cli
brew "gh"                       # github cli
cask "github"                   # github client
# brew "gradle"                   # java build tool
# cask "hoppscotch"               # rest client
brew "httpie"                   # cli rest client
cask "httpie"                   # rest client
brew "hurl"                     # cli rest client and test suite
cask "linear-linear"            # issue tracker
brew "oven-sh/bun/bun"          # js runtime and tooling
brew "pkgxdev/made/pkgx"        # everything runner
brew "podman"                   # container cli
cask "podman-desktop"           # container client
# brew "postgresql"               # postgres DB
brew "pre-commit"               # git hook manager
brew "pyenv"                    # python version manager
brew "rustup-init"              # rust toolchain installer
brew "scc"                      # lines of code counter
cask "temurin"                  # jdk
# cask "vagrant"                  # virtual env manager
# brew "vercel-cli"               # deployments and hosting

################################################################
# fonts                                                        #
################################################################

cask "font-anonymous-pro"
cask "font-anonymice-nerd-font"
# cask "font-cascadia-code"
# cask "font-caskaydia-cove-nerd-font"
# cask "font-fira-code"
# cask "font-fira-code-nerd-font"

################################################################
# games                                                        #
################################################################

# cask "clone-hero"               # guitar hero clone
brew "ferium"                   # minecraft mod manager
cask "minecraft"                # minecraft launcher
cask "modrinth"                 # minecraft launcher & mod manager
brew "quilt-installer"          # minecraft mod loader
# cask "retroarch"                # game emulator launcher
cask "steam"                    # game marketplace and launcher

################################################################
# new additions (via "brew add")                               #
################################################################
