# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-added-large-files
      - id: check-shebang-scripts-are-executable
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.16.2
    hooks:
      - id: gitleaks
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.6
    hooks:
      - id: prettier
  - repo: https://github.com/returntocorp/semgrep
    rev: v1.17.1
    hooks:
      - id: semgrep
        args: ["--config", "auto", "--error", "--skip-unknown-extensions"]
