#!/bin/bash

set -e

# install xcode tools
xcode-select --install

################################################################
# preferences -> general                                       #
################################################################

# dark mode
defaults write -g AppleInterfaceStyle -string "Dark"

# blue accent color
# defaults write -g AppleAccentColor -int 4

# highlight color
# accent color is default

# medium sized sidebars
defaults write -g NSTableViewDefaultSizeMode -int 2

# allow wallpaper tinting in windows
defaults write -g AppleReduceDesktopTinting -int 0

# automatic scrollbars
defaults write -g AppleShowScrollBars -string "Automatic"

# click on scrollbar jumps to spot clicked
defaults write -g AppleScrollerPagingBehavior -bool true

# disable open in new tab when opening new documents
defaults write -g AppleWindowTabbingMode -string "manual"

# always ask to confirm changes on close
defaults write -g NSCloseAlwaysConfirmsChanges -bool true

# always close windows on quit app
defaults write -g NSQuitAlwaysKeepsWindows -bool true

# set recent items limit
# TODO: double check domain and key for this one
# defaults write -g NSRecentDocumentsLimit -int 0

# allow handoff between icloud devices
# TODO: find domain and key for this

################################################################
# preferences -> desktop & screen saver                        #
################################################################

################################################################
# preferences -> dock & menu bar                               #
################################################################

# set dock icon size - reboot required
defaults write com.apple.dock tilesize -int 36

# enable dock magnification on hover
defaults write com.apple.dock magnification -bool true

# set dock icon magnification size
defaults write com.apple.dock largesize -int 42

# set dock location to bottom
defaults write com.apple.dock orientation -string "bottom"

# set scale minimize/maximize window effect
defaults write com.apple.dock mineffect -string "scale"

# enable double click window title bar to minimize
defaults write -g AppleActionOnDoubleClick -string "Minimize"

# minimize windows into their app icon
defaults write com.apple.dock minimize-to-application -bool true

# enable app launch animation
defaults write com.apple.dock launchanim -bool true

# disable auto hide and show dock
defaults write com.apple.dock autohide -bool false

# enable show process indicators for open apps
defaults write com.apple.dock show-process-indicators -bool true

# show recents
defaults write com.apple.dock show-recents -bool false



# finder & desktop

PLISTBUDDY=/usr/libexec/PlistBuddy
FINDERPLIST=~/Library/Preferences/com.apple.finder.plist

# enable snap-to-grid for icons on the desktop and in other icon views
$PLISTBUDDY -c "Set :DesktopViewSettings:IconViewSettings:arrangeBy grid" $FINDERPLIST
$PLISTBUDDY -c "Set :FK_StandardViewSettings:IconViewSettings:arrangeBy grid" $FINDERPLIST
$PLISTBUDDY -c "Set :StandardViewSettings:IconViewSettings:arrangeBy grid" $FINDERPLIST

# set grid spacing for icons on the desktop and in other icon views
$PLISTBUDDY -c "Set :DesktopViewSettings:IconViewSettings:gridSpacing 12" $FINDERPLIST
$PLISTBUDDY -c "Set :FK_StandardViewSettings:IconViewSettings:gridSpacing 12" $FINDERPLIST
$PLISTBUDDY -c "Set :StandardViewSettings:IconViewSettings:gridSpacing 12" $FINDERPLIST

# set the size of icons on the desktop and in other icon views
$PLISTBUDDY -c "Set :DesktopViewSettings:IconViewSettings:iconSize 36" $FINDERPLIST
$PLISTBUDDY -c "Set :FK_StandardViewSettings:IconViewSettings:iconSize 36" $FINDERPLIST
$PLISTBUDDY -c "Set :StandardViewSettings:IconViewSettings:iconSize 36" $FINDERPLIST

# show icon preview on the desktop and in other icon views
$PLISTBUDDY -c "Set :DesktopViewSettings:IconViewSettings:showIconPreview 1" $FINDERPLIST
$PLISTBUDDY -c "Set :FK_StandardViewSettings:IconViewSettings:showIconPreview 1" $FINDERPLIST
$PLISTBUDDY -c "Set :StandardViewSettings:IconViewSettings:showIconPreview 1" $FINDERPLIST



# finder: show hidden files
defaults write com.apple.finder AppleShowAllFiles --bool true

# finder: show all file extensions
defaults write NSGlobalDomain AppleShowAllExtensions -bool true

# finder: keep folders on top when sorting by name
defaults write com.apple.finder _FXSortFoldersFirst -bool true

# finder: use list view in all windows
defaults write com.apple.finder FXPreferredViewStyle -string "Nlsv"

# finder: allow quitting via ⌘ + Q; doing so will also hide desktop icons
defaults write com.apple.finder QuitMenuItem -bool true


# install homebrew
echo "Install Homebrew"
if test ! "$(which brew)"; then
    echo "Installing homebrew..."
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

# install tools and apps with brew
set +e
echo "Install from Brewfile"
export PATH=$PATH:/usr/local/bin
brew bundle --file Brewfile
set -e

# setup brew autoupdate

# install dotfiles

# find somewhere to specify alfred preferences setup and other apps/shortcuts