
format = '''$os\($shell\) at $all'''

[character]
success_symbol = "[](bold green)"
error_symbol = "[](bold red)"

[directory]
style = "bold blue"
read_only = " "

[git_branch]
symbol = " "
style = "bold white"

[hostname]
ssh_symbol = "  "

[os]
disabled = false

[package]
symbol = "  "

[python]
symbol = "  "
style = "bold green"

[rust]
symbol = "  "

[shell]
style = "purple"
format = "[$indicator]($style)"
disabled = false

[sudo]
symbol = "  "
