[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"

[directory]
style = "bold blue"

[git_branch]
style = "bold white"

[python]
style = "bold green"

[shell]
style = "purple"
disabled = false
