# ------------------------------------------------------------ #
# Brewfile - macOS package installation via homebrew           #
# ------------------------------------------------------------ #

# terminal apps and packages --------------------------------- #

brew "aliae"                          # shell manager
brew "bitwarden-cli"                  # password manager
brew "bjarneo/cliamp/cliamp"          # music player/streamer
# brew "cookcli"                        # recipe manager
brew "eza"                            # ls replacement
brew "fd"                             # find alternative
brew "fish"                           # a fun shell
brew "fzf"                            # fuzzy finder
brew "git"                            # version controller
brew "jq"                             # json processor
brew "lazygit"                        # git client
brew "mole"                           # system cleaner
brew "neovim"                         # text editor
# brew "ollama"                         # ai model server
brew "opencode"                       # ai coding agent
brew "presenterm"                     # markdown presenter
brew "ripgrep"                        # grep alternative
brew "boldandbrad/tap/slinky"         # dotfile manager
brew "boldandbrad/tap/spin"           # last.fm scrobbler
brew "starship"                       # shell prompt engine
brew "tmux"                           # terminal multiplexer
brew "zoxide"                         # cd replacement

# desktop apps ----------------------------------------------- #

cask "nikitabobko/tap/aerospace"      # tiling window manager
# cask "audacity"                       # audio toolkit
cask "bitwarden"                      # password manager
# cask "bricklink-studio"               # lego moc designer
cask "discord"                        # digital community client
cask "ghostty"                        # terminal emulator
cask "obsidian"                       # note manager
brew "FelixKratz/formulae/sketchybar" # menubar replacement
cask "tailscale-app"                  # homelab network manager
cask "tidal"                          # music streamer
# cask "tolaria"                        # note manager
cask "zed"                            # text editor

# software development tools and apps ------------------------ #

brew "bun"                      # js runtime & toolchain
brew "deno"                     # js runtime & toolchain
brew "gh"                       # cli github client
brew "go"                       # go compiler & toolchain
# cask "godot"                    # game engine
brew "lua"                      # lua language
brew "lua-language-server"      # lua language server
brew "marksman"                 # markdown lsp
brew "resterm"                  # http client
brew "taplo"                    # toml toolchain
cask "temurin"                  # java development kit
brew "tokei"                    # code line counter
brew "tree-sitter-cli"          # treesitter parser cli

# fonts ------------------------------------------------------ #

# cask "font-anonymous-pro"
# cask "font-cascadia-code"
# cask "font-commit-mono"
# cask "font-fantasque-sans-mono"
# cask "font-fira-code"
# cask "font-maple-mono"
# cask "font-roboto-mono"
cask "font-space-mono"
# cask "font-victor-mono"

# games ------------------------------------------------------ #

cask "minecraft"                # official minecraft launcher
# cask "retroarch"                # game emulator launcher
cask "steam"                    # game marketplace and launcher

# new additions (via "brew bundle add") ---------------------- #
