#!/bin/zsh

# tool replacements
alias cat="bat"
alias code="codium"
alias docker="podman"
alias ls="exa --classify"
alias la="exa --all --classify"
alias ll="exa --all --long --classify"
alias lt="exa --tree --classify --sort=type"
alias lta="exa --all --tree --classify --sort=type"
alias ld="exa --only-dirs --classify"
alias lda="exa --all --only-dirs --classify"
alias rm="trash" # prefer safer mv to trash function over rm

# navigation shortcuts
alias ..="cd .."
alias ...="cd ../.."
alias -- -="cd -"
alias ap="cd /Applications"
alias dt="cd ~/Desktop"
alias dv="cd ~/Developer"
alias dc="cd ~/Documents"
alias dl="cd ~/Downloads"
alias sp="cd ~/Setup"
alias dots="cd $DOTFILES"

# other replacements
alias mkdir="mkdir -pv"
alias mv="mv -iv"
alias cp="cp -Riv"
alias cwd="pwd | pbcopy"
alias reload=". ~/.zshrc"
alias awake="caffeinate" # macos only
alias dust="dust -r"
alias finder="open ." # open pwd in Finder

# remove brew doctor warning (https://github.com/pyenv/pyenv#homebrew-in-macos)
# alias brew='env PATH="${PATH//$(pyenv root)\/shims:/}" brew'

# dotfile refresh
alias refresh="dotbot -c $DOTFILES/install.conf.yaml"

# gh repo clone refresh
alias clone="source $DOTFILES/gh/install.zsh"

# codium extension export and install
alias codexp="codium --list-extensions > $DOTFILES/vscodium/extensions.txt && echo '\tExported VSCodium extensions list to DOTFILES.'"
alias codein="source $DOTFILES/vscodium/install.zsh"

# pretty print PATH
alias path='echo $PATH | tr -s ":" "\n"'
alias fpath='echo $FPATH | tr -s ":" "\n"'

# glow markdown viewer with pager
alias glow="glow -p"

# quicklook from the terminal
alias ql="qlmanage -p ${@} > /dev/null 2> /dev/null"

# browsers
alias safari="open -a Safari"
alias firefox="open -a Firefox"

# activate python venv in the current directory
alias pysrc="source .venv/bin/activate"
