# .zshrc

# source antidote and initialize zsh plugins
source $(brew --prefix)/opt/antidote/share/antidote/antidote.zsh
zstyle ':antidote:bundle' file $HOME/.config/zsh/.plugins
antidote load

# allow tab completion menu selection
zstyle ':completion:*' menu select

# allow partial tab completions: cd /u/lo/b⇥ -> /usr/local/bin
zstyle ':completion:*' list-suffixes zstyle ':completion:*'

# initialize zsh completions
autoload -Uz compinit
compinit

# meeple-cli completions
eval "$(_MEEPLE_COMPLETE=zsh_source meeple)"

# load dotfiles
for DOTFILE in ~/.config/zsh/.{aliases,functions,options}; do
  [ -f "$DOTFILE" ] && source "$DOTFILE"
done

# initialize autojump
[ -f /usr/local/etc/profile.d/autojump.sh ] && source /usr/local/etc/profile.d/autojump.sh

# initialize direnv
if (( $+commands[direnv] )); then
  eval "$(direnv hook zsh)"
fi

# initialize fnm
if (( $+commands[fnm] )); then
  eval "$(fnm env --use-on-cd)"
fi

# initialize pyenv
if (( $+commands[pyenv] )); then
  eval "$(pyenv init -)"
fi

# initialize starship
if (( $+commands[starship] )); then
  eval "$(starship init zsh)"
fi

source <(pkgx --shellcode)  # docs.pkgx.sh/shellcode

# remove duplicates from path arrays
typeset -gU PATH FPATH
