# Fig pre block. Keep at the top of this file.
[[ -f "$HOME/.fig/shell/zshrc.pre.zsh" ]] && . "$HOME/.fig/shell/zshrc.pre.zsh"

# load dotfiles
for DOTFILE in ~/.config/zsh/.{aliases,functions,zoptions}; do
  [ -f "$DOTFILE" ] && source "$DOTFILE"
done

# initialize pyenv
if (( $+commands[pyenv] )); then
  eval "$(pyenv init -)"
fi

# initialize rbenv
if (( $+commands[rbenv] )); then
  eval "$(rbenv init - zsh)"
fi

# fnm
if (( $+commands[fnm] )); then
  eval "$(fnm env --use-on-cd)"
fi

# travis tab completions
[ ! -s ~/.travis/travis.sh ] || . ~/.travis/travis.sh

# brew setup
if (( $+commands[brew] )); then
  # brew autocompletion
  FPATH=$(brew --prefix)/share/zsh/site-functions:$FPATH

  # zsh auto suggestions
  . $(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh

  # zsh syntax highlighting
  . $(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

  autoload -Uz compinit
  compinit
fi

HB_CNF_HANDLER="$(brew --repository)/Library/Taps/homebrew/homebrew-command-not-found/handler.sh"
if [ -f "$HB_CNF_HANDLER" ]; then
  source "$HB_CNF_HANDLER";
fi

# pipx bash tab completions
if (( $+commands[pipx] )); then
  autoload -U bashcompinit
  bashcompinit
  eval "$(register-python-argcomplete pipx)"
fi

# auto jump
[ -f /usr/local/etc/profile.d/autojump.sh ] && . /usr/local/etc/profile.d/autojump.sh

# starship prompt
eval "$(starship init zsh)"

# direnv hook
eval "$(direnv hook zsh)"

# remove duplicates from PATH and FPATH
typeset -U PATH
typeset -U FPATH

# Fig post block. Keep at the bottom of this file.
[[ -f "$HOME/.fig/shell/zshrc.post.zsh" ]] && . "$HOME/.fig/shell/zshrc.post.zsh"
