# Fig pre block. Keep at the top of this file.
[[ -f "$HOME/.fig/shell/bashrc.pre.bash" ]] && builtin source "$HOME/.fig/shell/bashrc.pre.bash"

# load aliases
# if [ -f ~/.aliases ]; then
# 	source ~/.aliases
# fi

[[ -f "$HOME/.cargo/env" ]] && . "$HOME/.cargo/env"

eval "$(direnv hook bash)"
eval "$(starship init bash)"

# Fig post block. Keep at the bottom of this file.
[[ -f "$HOME/.fig/shell/bashrc.post.bash" ]] && builtin source "$HOME/.fig/shell/bashrc.post.bash"
