# ------------------------------------------------------------ #
# tmux config                                                  #
# docs: https://github.com/tmux/tmux/wiki/Getting-Started      #
# ------------------------------------------------------------ #

# prefix

set -g prefix C-Space
unbind C-b
bind C-Space send-prefix

# options

set -s escape-time 0
set -g display-time 2000
set -g status-interval 5
set -s default-terminal "screen-256color"
set -g focus-events on

set -g set-titles on

set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set -g renumber-windows on

# keybinds

bind s split-window
bind v split-window -h

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind p previous-window
bind n next-window

bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded tmux config!"

# status bar

set -g status-justify centre
set -g status-style bg=default
set -g status-left '#[bg=#a6e3a1]#[fg=#1e1e2e,bold] #S '
set -g status-right ''

setw -g window-status-current-format '#[bg=#fab387]#[fg=#1e1e2e,bold] #I #[bg=#45475a]#[fg=default] #W '
setw -g window-status-format '#[bg=#89b4fa]#[fg=#1e1e2e] #I #[bg=#313244]#[fg=default] #W '
